### PR TITLE
upgraded webpack-dev-server - HMR and tests work

### PR DESCRIPTION
**Pull request by lukephills**
You were right, upgrading webpack-dev-server did the trick! The tests were failing with the updated version because it couldn't handle the es6 destructuring in the webpack karma config file.

### CODE REVIEW

**Comment by Kflash** [comment]
Sounds great! Can you do "npm run browser" and verify that the browser
tests works after the update? No proxy issue?

**Comment by lukephills** [comment]
`npm run browser` was failing on the 'target' option issue. So I added a target for it and it runs. `npm test` runs both tests fine. What is the `npm run browser` task used for?

**Comment by Kflash** [comment]
The npm run browser task let you see the browser tests on port 8080.

You have write access to the repo

Great work!!

**Comment by Kflash** [comment]
@lukephills Amazing work! I will dig into this now, and try to lift this boilerplate up to another level now. Btw. Do you think Angular 2 and React should be supported 100%?

**Comment by Kflash** [comment]
@lukephills HMR works for you? When I did changes in the app.ts, no changes happend to me?? I even tried to change the name on the app.

**Comment by Kflash** [comment]
@lukephills I'm done so far with the repo / experimental code I linked to above. Can you test it and let me know if it works as you want it? If it do so, I will add TypeScript stuff etc.

**Pull request merged**
